import jasonimg from '../../assets/img/jasonimg';
import Footer from '../../components/footer/Footer';
import Header from '../../components/header/Header';
import './Privacity.css';

function Privacity() {
    return (
        <>
            <body>
             <Header />
                <div className="title-container">
                    <div className="title-text">
                        <h1 className="title">PRIVACITY POLICY</h1>
                    </div>
                    <div className="title-img">
                        <img src={jasonimg[12]} />
                    </div>
                </div>
                <h1></h1>
                <div className="privacity-container">
                    <div className="privacity-item">
                        <p>EN</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>FIRST.- The services that make up this website for users are free of charge and do not require prior registration.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>SECOND.- By the mere use of the OrbitWaste blog, the user expresses his unreserved acceptance of these general conditions.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>THIRD.- The user undertakes not to use the services offered by this blog to carry out illegal activities or that violate public order and, in general, agrees to use them in accordance with these general conditions.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>FOURTH.- OrbitWaste is not responsible for the content generated by users in the news section.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>FIFTH.- The user undertakes to respect the restrictions on the use of the service imposed by OrbitWaste and the moderation policy of the blog.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>SIXTH.- OrbitWaste will not be responsible for failures that may occur in communications, including deletion, incomplete transmission or delays in remittance, nor is it committing itself to ensuring that the transmission network is operational at all times. Nor will OrbitWaste be liable in the event that a third party, violating the security measures established by OrbitWaste, accesses the content submitted by the user or uses it for the referral of computer viruses.
                            OrbitWaste has adopted all the security measures legally required for the protection of personal data provided by the user. However, OrbitWaste cannot guarantee the absolute invulnerability of its security systems, nor can it guarantee the security or inviolability of said data in its transmission through the network.
                            The links that the website makes available to users have the sole purpose of making it easier for them to search for information available on the Internet. OrbitWaste does not offer or market the products and services available on the linked sites and assumes no responsibility for such products or services.
                            OrbitWaste does not control the use that users make of the web, nor does it guarantee that they do so in accordance with these conditions.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>SEVENTH.- OrbitWaste may interrupt the service or immediately terminate the relationship with the user if it detects use of its portal or any of the services offered therein contrary to these general conditions.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>EIGHTH.- OrbitWaste reserves the right to stop providing any of the services that make up its website. It also reserves the right to unilaterally modify, at any time and without prior notice, the presentation and conditions of the portal, as well as the services and conditions required for its use.</p>
                        <br />
                    </div>
                    <div className="privacity-item">
                        <p>NINTH.- OrbitWaste may, at any time, modify these conditions or introduce new conditions of use, including the termination of gratuity. Said modifications will only be applicable from their entry into force.</p>
                        <br />
                    </div>
                </div>
                <Footer />
            </body>
        </>
    );
};

export default Privacity;