import jasonimg from "../../assets/img/jasonimg";
import Footer from "../../components/footer/Footer";
import Header from "../../components/header/Header";
import "./Starship.css";

function Starship() {
    return (
        <>
            <body>
                <Header />
                <div className="title-container">
                    <div className="title-text">
                        <h1 className="title">STARSHIP</h1>
                    </div>
                    <div className="title-img">
                        <img src={jasonimg[9]} />
                    </div>
                </div>
                <div className="starship-body">
                    <div className="starship-container">
                        <div class="starship-items">
                            <div className="starship-item-text">
                                <h2>ABOUT THE STARSHIP</h2>
                                <p>
                                    Having a large and easily reusable rocket is not the only contribution that Elon Musk's space company makes. SpaceX is bringing other innovations to rocket design. One of them is the ingenious separation system of the Starship and its Super Heavy propellant, designed to lighten the weight of the rocket and solve some problems generated by the separation systems used up to now, which in some cases generated space debris that could damage the rocket itself, and in others they put the integrity of the rocket at risk.
                                </p>
                            </div>
                            <div className="starship-item-img">
                                <img src={jasonimg[11]} />
                            </div>
                        </div>
                        <div class="starship-items">
                            <div className="starship-item-text">
                                <h2>Why is Starship so important?</h2>
                                <p>
                                    The project to create a "completely and rapidly reusable orbital-class rocket that can be mass-produced" goes much further, and will allow for fewer new pieces of space junk in the near future.
                                </p>
                            </div>
                            <div className="starship-item-img">
                                <img src={jasonimg[10]} />
                            </div>
                            <div className="starship-item-text">
                                <h2>HOW IT WORKS:</h2>
                            </div>
                            <div className="starship-item-video">
                                <iframe
                                    src="https://www.youtube.com/embed/HcjPNHkVI0o?feature=oembed"
                                    title="YouTube video player"
                                    frameborder="0"
                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                    allowfullscreen
                                ></iframe>
                            </div>
                        </div>
                    </div>
                </div>
                <Footer />
            </body>
        </>
    );
};

export default Starship;